#!/usr/bin/env python3
# SPDX-License-Identifier: AGPL-3.0-only
"""Generate ``docs/authoring/Manifest.md`` from the manifest's Pydantic models.

The page is a rendering of ``backend/app/agents/manifest.py`` — every
model, every field with its type, whether it is required, its default,
its constraints — and of the prose the module already carries: each
model's docstring, each model validator's docstring (the rules), and the
comment block written directly above a field's declaration. Nothing on
the page is typed twice: a field added to a model appears here on the
next run, and a page that does not match the models fails the drift
check (``--check``, run by ``backend/tests/test_manifest_reference.py``).

Run from ``backend/`` (the models import the chassis):

    cd backend && python ../scripts/export_manifest_reference.py           # rewrite the page
    cd backend && python ../scripts/export_manifest_reference.py --check   # exit 1 when it differs

The models are walked from ``AgentManifest`` outward, in the order a
reader meets them, so a nested model is documented after the field that
introduces it.
"""
from __future__ import annotations

import argparse
import ast
import inspect
import sys
import textwrap
import types
import typing
from pathlib import Path

HERE = Path(__file__).resolve().parent
REPO = HERE.parent
BACKEND = REPO / "backend"
PAGE = REPO / "docs" / "authoring" / "Manifest.md"

if str(BACKEND) not in sys.path:
    sys.path.insert(0, str(BACKEND))

from pydantic import BaseModel  # noqa: E402
from pydantic_core import PydanticUndefined  # noqa: E402

from app.agents import manifest as manifest_module  # noqa: E402
from app.agents.manifest import AgentManifest  # noqa: E402

HEADER = """\
# The agent manifest (`agent.yaml`) — field reference

<!-- GENERATED by scripts/export_manifest_reference.py from
     backend/app/agents/manifest.py. Do not edit: a change to the models
     regenerates this page, and CI fails when the two differ.
     Regenerate:  cd backend && python ../scripts/export_manifest_reference.py -->

Every agent directory ships an `agent.yaml`. The chassis reads it at
discovery and refuses to register an agent whose manifest does not
validate against the models below — `agent_manifest_invalid` in the
backend log names the field. `librerun init` renders a complete one
from each of its templates; `docs/authoring/Agents_Design.md` is the behavioural
contract the fields refer to.

Types are Python's, as the models declare them; `list[...]` is a YAML
sequence, a nested model a YAML mapping. Unknown keys are refused
everywhere (`extra="forbid"`). A field with no default is required.
"""


def _md(text: str) -> str:
    """Docstrings are written in RST (``double`` backticks); the page is
    Markdown, where one backtick is the literal."""
    return text.replace("``", "`")


def _field_comments(module) -> dict[tuple[str, str], str]:
    """The comment block directly above each field declaration, per
    ``(model, field)``, read from the module's source."""
    source = inspect.getsource(module)
    lines = source.splitlines()
    tree = ast.parse(source)
    found: dict[tuple[str, str], str] = {}
    for node in tree.body:
        if not isinstance(node, ast.ClassDef):
            continue
        for item in node.body:
            if not isinstance(item, ast.AnnAssign) or not isinstance(item.target, ast.Name):
                continue
            block: list[str] = []
            row = item.lineno - 2  # the line above the declaration, 0-based
            while row >= 0:
                text = lines[row].strip()
                if text.startswith("#"):
                    block.insert(0, text.lstrip("#").strip())
                    row -= 1
                    continue
                break
            if block:
                found[(node.name, item.target.id)] = _md(" ".join(block))
    return found


def _type_name(annotation) -> str:
    if annotation is None or annotation is type(None):
        return "None"
    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)
    if origin is typing.Literal:
        return " \\| ".join(f"`{a!r}`" for a in args)
    if origin in (typing.Union, types.UnionType):
        return " \\| ".join(_type_name(a) for a in args)
    if origin is not None:
        inner = ", ".join(_type_name(a) for a in args)
        return f"{getattr(origin, '__name__', str(origin))}[{inner}]"
    if inspect.isclass(annotation) and issubclass(annotation, BaseModel):
        return f"[`{annotation.__name__}`](#{annotation.__name__.lower()})"
    return getattr(annotation, "__name__", str(annotation))


def _default(field) -> str:
    if field.is_required():
        return "**required**"
    if field.default_factory is not None:
        try:
            value = field.default_factory()
        except Exception:  # noqa: BLE001 — a factory that needs arguments
            return "(computed)"
        if isinstance(value, BaseModel):
            return "the model's defaults"
        return f"`{value!r}`" if value not in ([], {}, "") else f"`{value!r}`"
    if field.default is PydanticUndefined:
        return "**required**"
    return f"`{field.default!r}`"


def _constraints(field) -> str:
    parts = []
    for meta in field.metadata:
        for name in ("pattern", "min_length", "max_length", "ge", "gt", "le", "lt", "strict"):
            value = getattr(meta, name, None)
            if value is not None and value is not False:
                parts.append(f"{name}=`{value}`" if name != "strict" else "strict")
    return ", ".join(parts) if parts else "—"


def _nested_models(model: type[BaseModel]) -> list[type[BaseModel]]:
    """The models this one's fields introduce, in field order."""
    out: list[type[BaseModel]] = []

    def walk(annotation):
        origin = typing.get_origin(annotation)
        if origin is not None:
            for arg in typing.get_args(annotation):
                walk(arg)
            return
        if inspect.isclass(annotation) and issubclass(annotation, BaseModel) and annotation not in out:
            out.append(annotation)

    for field in model.model_fields.values():
        walk(field.annotation)
    return out


def _ordered_models() -> list[type[BaseModel]]:
    ordered: list[type[BaseModel]] = []
    queue = [AgentManifest]
    while queue:
        model = queue.pop(0)
        if model in ordered:
            continue
        ordered.append(model)
        queue.extend(m for m in _nested_models(model) if m not in ordered)
    return ordered


def _rules(model: type[BaseModel]) -> list[str]:
    """Each validator's docstring: the rules the fields are held to."""
    rules = []
    decorators = model.__pydantic_decorators__
    for group in (decorators.model_validators, decorators.field_validators):
        for name, decorator in group.items():
            doc = inspect.getdoc(decorator.func)
            if doc:
                rules.append(_md(doc.strip()))
    return rules


def render() -> str:
    comments = _field_comments(manifest_module)
    out = [HEADER]
    out.append("## Models\n")
    for model in _ordered_models():
        out.append(f"- [`{model.__name__}`](#{model.__name__.lower()})")
    out.append("")
    for model in _ordered_models():
        out.append(f"## `{model.__name__}`\n")
        doc = inspect.getdoc(model)
        if doc and doc != inspect.getdoc(BaseModel):
            out.append(_md(textwrap.dedent(doc).strip()) + "\n")
        out.append("| Field | Type | Default | Constraints | Notes |")
        out.append("|---|---|---|---|---|")
        for name, field in model.model_fields.items():
            note = comments.get((model.__name__, name), "—")
            out.append(
                f"| `{name}` | {_type_name(field.annotation)} | {_default(field)} | "
                f"{_constraints(field)} | {note} |"
            )
        out.append("")
        rules = _rules(model)
        if rules:
            out.append("**Rules**\n")
            for rule in rules:
                first, _, rest = rule.partition("\n")
                body = (" ".join(rest.split())).strip()
                out.append(f"- {first.strip()}" + (f" {body}" if body else ""))
            out.append("")
    reserved = getattr(manifest_module, "RESERVED_STEP_IDS", ())
    if reserved:
        out.append("## Reserved step ids\n")
        out.append(
            "The platform owns these `llm.steps[].id` values; a manifest that "
            "declares one is refused: " + ", ".join(f"`{r}`" for r in reserved) + ".\n"
        )
    return "\n".join(out).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--check", action="store_true", help="exit 1 when the page differs from the models")
    parser.add_argument("--output", default=str(PAGE), help=f"where to write (default {PAGE})")
    args = parser.parse_args(argv)
    text = render()
    target = Path(args.output)
    if args.check:
        current = target.read_text(encoding="utf-8") if target.is_file() else ""
        if current != text:
            print(
                f"{target} is out of date with backend/app/agents/manifest.py: "
                f"run `cd backend && python ../scripts/export_manifest_reference.py`",
                file=sys.stderr,
            )
            return 1
        print(f"{target} matches the models")
        return 0
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(text, encoding="utf-8")
    print(f"wrote {target}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
